---
ci:
  autoupdate_schedule: monthly

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        language: python
        additional_dependencies: [uv]
        entry: uv run -m ruff check --fix --exit-non-zero-on-fix
        files: ^.*\.(py|md)$

      - id: ruff-format
        name: ruff format
        language: python
        additional_dependencies: [uv]
        entry: uv run -m ruff format --exit-non-zero-on-format
        files: ^.*\.py$

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.29
    hooks:
      - id: uv-lock

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        args: [tests]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".*\\.svg$"
      - id: check-toml
      - id: check-yaml
